In [2]:
from infos import *
import simfin as sf
verofsimfin = sf.__version__
print('''
사용하는 Simfin 패키지의 버전은 {}
'''.format(verofsimfin))
# 파일의 디렉토리 설정
sf.set_data_dir('./SimfinData/')
sf.set_api_key(simfin_api)

사용하는 Simfin 패키지의 버전은 0.8.1

In [11]:
# 데이터를 다운로드하는 구절
company = sf.load_companies(market='us')
industry = sf.load_industries()
income = sf.load_income(variant='quarterly-full', market='us')
balance = sf.load_balance(variant='quarterly-full', market='us')
cash = sf.load_cashflow(variant='quarterly-full', market='us')
priceratio = sf.load_derived_shareprices(variant='latest', market='us')
price = sf.load_shareprices(variant='daily', market='us')

Dataset "us-companies" on disk (0 days old).
- Loading from disk ... Done!
Dataset "industries" on disk (0 days old).
- Loading from disk ... Done!
Dataset "us-income-quarterly-full" on disk (0 days old).
- Loading from disk ... Done!
Dataset "us-balance-quarterly-full" on disk (0 days old).
- Loading from disk ... Done!
Dataset "us-cashflow-quarterly-full" on disk (0 days old).
- Loading from disk ... Done!
Dataset "us-derived-shareprices-latest" on disk (0 days old).
- Loading from disk ... Done!
Dataset "us-shareprices-daily" on disk (0 days old).
- Loading from disk ... Done!

In [24]:
company = sf.load_companies(market='us')
company2 = company.reset_index()
data = company2.astype(str).values.tolist()
data[:2]

Dataset "us-companies" on disk (0 days old).
- Loading from disk ... Done!

[['A', '45846', 'AGILENT TECHNOLOGIES INC', '106001.0'],
 ['AA', '367153', 'Alcoa Corp', '110004.0']]

In [27]:
industry = sf.load_industries()
data = industry.reset_index().fillna(0).head()

Dataset "industries" on disk (0 days old).
- Loading from disk ... Done!

In [39]:
import pandas as pd 
income = sf.load_income(variant='quarterly-full', market='us')
# pd.melt(income)
income

Dataset "us-income-quarterly-full" on disk (0 days old).
- Loading from disk ... Done!

                    SimFinId Currency  Fiscal Year Fiscal Period Publish Date  \
Ticker Report Date
A      2010-07-31      45846      USD         2010            Q3   2010-09-07
       2010-10-31      45846      USD         2010            Q4   2010-12-08
       2011-01-31      45846      USD         2011            Q1   2011-03-09
       2011-04-30      45846      USD         2011            Q2   2011-06-07
       2011-07-31      45846      USD         2011            Q3   2011-09-07
...                      ...      ...          ...           ...          ...
ZYXI   2019-09-30     171401      USD         2019            Q3   2019-10-29
       2019-12-31     171401      USD         2019            Q4   2020-02-27
       2020-03-31     171401      USD         2020            Q1   2020-04-28
       2020-06-30     171401      USD         2020            Q2   2020-07-28
       2020-09-30     171401      USD         2020            Q3   2020-10-27

                   Restated Date  Shares (Basic)  Shares (Diluted)  \
Ticker Report Date
A      2010-07-31     2011-09-07     347000000.0       352000000.0
       2010-10-31     2012-12-20     344000000.0       356000000.0
       2011-01-31     2012-03-05     347000000.0       355000000.0
       2011-04-30     2012-06-04     347000000.0       355000000.0
       2011-07-31     2012-09-05     348000000.0       357000000.0
...                          ...             ...               ...
ZYXI   2019-09-30     2019-10-29      32490000.0        34076000.0
       2019-12-31     2020-02-27      32707000.0        34102000.0
       2020-03-31     2020-04-28      32913000.0        34204000.0
       2020-06-30     2020-07-28      33283000.0        34454000.0
       2020-09-30     2020-10-27      34486000.0        35476000.0

                                                               Source  \
Ticker Report Date
A      2010-07-31   http://www.sec.gov/Archives/edgar/data/1090872...
       2010-10-31   http://www.sec.gov/Archives/edgar/data/1090872...
       2011-01-31   http://www.sec.gov/Archives/edgar/data/1090872...
       2011-04-30   http://www.sec.gov/Archives/edgar/data/1090872...
       2011-07-31   http://www.sec.gov/Archives/edgar/data/1090872...
...                                                               ...
ZYXI   2019-09-30   https://www.sec.gov/Archives/edgar/data/846475...
       2019-12-31   https://www.sec.gov/Archives/edgar/data/846475...
       2020-03-31   https://www.sec.gov/Archives/edgar/data/846475...
       2020-06-30   https://www.sec.gov/Archives/edgar/data/846475...
       2020-09-30   https://www.sec.gov/Archives/edgar/data/846475...

                         Revenue  ...  \
Ticker Report Date                ...
A      2010-07-31   1.384000e+09  ...
       2010-10-31   1.576000e+09  ...
       2011-01-31   1.519000e+09  ...
       2011-04-30   1.677000e+09  ...
       2011-07-31   1.691000e+09  ...
...                          ...  ...
ZYXI   2019-09-30   1.181700e+07  ...
       2019-12-31   1.416200e+07  ...
       2020-03-31   1.522800e+07  ...
       2020-06-30   1.926300e+07  ...
       2020-09-30   2.002600e+07  ...

                    Income (Loss) from Continuing Operations  \
Ticker Report Date
A      2010-07-31                                  205000000
       2010-10-31                                  292000000
       2011-01-31                                  193000000
       2011-04-30                                  200000000
       2011-07-31                                  330000000
...                                                      ...
ZYXI   2019-09-30                                    2031000
       2019-12-31                                    2949000
       2020-03-31                                    2937000
       2020-06-30                                    3017000
       2020-09-30                                    1333000

                    Net Extraordinary Gains (Losses)  Discontinued Operations  \
Ticker Report Date
A      2010-07-31                                NaN                      NaN
       2010-10-31                                NaN                      NaN
       2011-01-31                                NaN                      NaN
       2011-04-30                                NaN                      NaN
       2011-07-31                                NaN                      NaN
...                                              ...                      ...
ZYXI   2019-09-30                                NaN                      NaN
       2019-12-31                                NaN                      NaN
       2020-03-31                                NaN                      NaN
       2020-06-30                                NaN                      NaN
       2020-09-30                                NaN                      NaN

                    Accounting Charges & Other  \
Ticker Report Date
A      2010-07-31                          NaN
       2010-10-31                          NaN
       2011-01-31                          NaN
       2011-04-30                          NaN
       2011-07-31                          NaN
...                                        ...
ZYXI   2019-09-30                          NaN
       2019-12-31                          NaN
       2020-03-31                          NaN
       2020-06-30                          NaN
       2020-09-30                          NaN

                    Income (Loss) Incl. Minority Interest  Minority Interest  \
Ticker Report Date
A      2010-07-31                               205000000                NaN
       2010-10-31                               292000000                NaN
       2011-01-31                               193000000                NaN
       2011-04-30                               200000000                NaN
       2011-07-31                               330000000                NaN
...                                                   ...                ...
ZYXI   2019-09-30                                 2031000                NaN
       2019-12-31                                 2949000                NaN
       2020-03-31                                 2937000                NaN
       2020-06-30                                 3017000                NaN
       2020-09-30                                 1333000                NaN

                    Net Income  Preferred Dividends  Other Adjustments  \
Ticker Report Date
A      2010-07-31    205000000                  NaN                NaN
       2010-10-31    292000000                  NaN                NaN
       2011-01-31    193000000                  NaN                NaN
       2011-04-30    200000000                  NaN                NaN
       2011-07-31    330000000                  NaN                NaN
...                        ...                  ...                ...
ZYXI   2019-09-30      2031000                  NaN                NaN
       2019-12-31      2949000                  NaN                NaN
       2020-03-31      2937000                  NaN                NaN
       2020-06-30      3017000                  NaN                NaN
       2020-09-30      1333000                  NaN                NaN

                    Net Income (Common)
Ticker Report Date
A      2010-07-31             205000000
       2010-10-31             292000000
       2011-01-31             193000000
       2011-04-30             200000000
       2011-07-31             330000000
...                                 ...
ZYXI   2019-09-30               2031000
       2019-12-31               2949000
       2020-03-31               2937000
       2020-06-30               3017000
       2020-09-30               1333000

[64045 rows x 67 columns]

In [45]:
income2 = pd.melt(income.reset_index(),id_vars=['Ticker','Report Date','SimFinId', 'Currency', 'Fiscal Year', 'Fiscal Period', 'Publish Date',
       'Restated Date', 'Shares (Basic)', 'Shares (Diluted)', 'Source'])
income2[['Report Date','Publish Date','Restated Date']] = income2[['Report Date','Publish Date','Restated Date']].astype(str)

        Report Date Publish Date Restated Date
0        2010-07-31   2010-09-07    2011-09-07
1        2010-10-31   2010-12-08    2012-12-20
2        2011-01-31   2011-03-09    2012-03-05
3        2011-04-30   2011-06-07    2012-06-04
4        2011-07-31   2011-09-07    2012-09-05
...             ...          ...           ...
3714605  2019-09-30   2019-10-29    2019-10-29
3714606  2019-12-31   2020-02-27    2020-02-27
3714607  2020-03-31   2020-04-28    2020-04-28
3714608  2020-06-30   2020-07-28    2020-07-28
3714609  2020-09-30   2020-10-27    2020-10-27

[3714610 rows x 3 columns]

In [54]:
priceratio = sf.load_derived_shareprices(variant='latest', market='us')
priceratio2 = pd.melt(priceratio.reset_index(),id_vars=['Ticker','Date','SimFinId'])
priceratio2['Date'] = priceratio2['Date'].astype(str)

Dataset "us-derived-shareprices-latest" on disk (0 days old).
- Loading from disk ... Done!

In [56]:
price.reset_index()

,Ticker,Date,SimFinId,Open,Low,High,Close,Adj. Close,Dividend,Volume,Shares Outstanding
0,A,2007-01-03,45846,34.99,34.05,35.48,34.30,22.76,NaN,2574600,NaN
1,A,2007-01-04,45846,34.30,33.46,34.60,34.41,22.83,NaN,2073700,NaN
2,A,2007-01-05,45846,34.30,34.00,34.40,34.09,22.62,NaN,2676600,NaN
3,A,2007-01-08,45846,33.98,33.68,34.08,33.97,22.54,NaN,1557200,NaN
4,A,2007-01-09,45846,34.08,33.63,34.32,34.01,22.57,NaN,1386200,NaN
...,...,...,...,...,...,...,...,...,...,...,...
6117886,ZYXI,2020-11-16,171401,13.93,13.22,13.93,13.44,13.44,NaN,662755,34740990.0
6117887,ZYXI,2020-11-17,171401,13.48,12.93,14.11,13.63,13.63,NaN,633935,34740990.0
6117888,ZYXI,2020-11-18,171401,13.78,13.45,13.96,13.56,13.56,NaN,307124,34740990.0
6117889,ZYXI,2020-11-19,171401,13.53,13.26,13.56,13.36,13.36,NaN,395623,34740990.0
6117890,ZYXI,2020-11-20,171401,13.27,13.05,13.63,13.42,13.42,NaN,445528,34740990.0